site_name: Thi-origin documentation

nav: 
    - Home: index.md
    - Libraries: libraries.md
    - Powers: powers.md
    - Origins: origins.md

theme: 
    name: readthedocs


extra_css:
    - assets/extra.css

markdown_extensions:
    - attr_list
